export interface Product{
  id: number,
  name: string,
  description: string,
  rating: number,
  images: number,
  price: number,
  memory: number,
  color: string,
  kaspiLink:string,
  sortType:string,
  like:number
}

export const products = [
  {
    id: 1,
    name: "Iphone12",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.77,
    images: 1,
    price: 380000,
    memory: 256,
    color: "purple",
    kaspiLink: "https://kaspi.kz/shop/p/apple-iphone-12-128gb-fioletovyi-101395751/?c=750000000#!/item",
    sortType: "phone",
    like:5
  },
  {
    id: 2,
    name: "Samsung A51",
    description: "Tested for battery health and guaranteed to have a minimum battery capacity of 80%. Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). ",
    rating: 3.5,
    images: 2,
    price: 164990,
    memory: 64,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/samsung-galaxy-a51-6-gb-128-gb-chernyi-100068493/?c=750000000#!/item",
    sortType: "phone",
    like:7
  },
  {
    id: 3,
    name: "Oppo A91",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.99,
    images: 3,
    price: 163990,
    memory: 128,
    color: "purple",
    kaspiLink: "https://kaspi.kz/shop/p/oppo-reno-7-8-gb-128-gb-oranzhevyi-104705825/?c=750000000#!/item",
    sortType: "phone",
    like:58
  },
  {
    id: 10,
    name: "Lenova IdeaPAD",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 2.9,
    images: 10,
    price: 164990,
    memory: 256,
    color: "green",
    kaspiLink: "https://kaspi.kz/shop/p/lenovo-ideapad-3-15itl6-82h8005grk-serebristyi-108090705/?c=750000000#!/item",
    sortType: "laptop",
    like:95
  },
  {
    id: 4,
    name: "Macbook Pro",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.5,
    images: 4,
    price: 993990,
    memory: 512,
    color: "green",
    kaspiLink: "https://kaspi.kz/shop/p/apple-macbook-pro-14-mkgp3-seryi-102866247/?c=750000000#!/item",
    sortType: "laptop",
    like:57
  },
  {
    id: 5,
    name: "Asus Rog",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.7,
    images: 5,
    price: 419990,
    memory: 512,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/asus-rog-strix-g15-g513ih-90nr07p2-m00160-seryi-101686597/?c=750000000#!/item",
    sortType: "laptop",
    like:78
  },
  {
    id: 6,
    name: "Acer Nitro 5",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.7,
    images: 6,
    price: 559990,
    memory: 512,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/acer-nitro-5-an515-45-nh-qbcer-005-chernyi-106111779/?c=750000000#!/item",
    sortType: "laptop",
    like:58
  },
  {
    id: 15,
    name: "ZIK Computers",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.5,
    images: 15,
    price: 89900,
    memory: 64,
    color: "white",
    kaspiLink: "https://kaspi.kz/shop/p/zik-computers-w-1167s-edu-009zik-belyi-100764189/?c=750000000#!/item",
    sortType: "laptop",
    like:852
  },
  {
    id: 16,
    name: "Lenovo IdeaPad 3",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.5,
    images: 16,
    price: 309990,
    memory: 512,
    color: "green",
    kaspiLink: "https://kaspi.kz/shop/p/zik-computers-w-1167s-edu-009zik-belyi-100764189/?c=750000000#!/item",
    sortType: "laptop",
    like:789
  },
  {
    id: 7,
    name: "Redmi note 9",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.9,
    images: 7,
    price: 128990,
    memory: 256,
    color: "red",
    kaspiLink: "https://kaspi.kz/shop/p/xiaomi-redmi-note-10-pro-8-gb-256-gb-seryi-107221005/?c=750000000#!/item",
    sortType: "phone",
    like:43
  },
  {
    id: 8,
    name: "Vivo Pro",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.2,
    images: 8,
    price: 319990,
    memory: 32,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/vivo-v25-pro-12-gb-256-gb-chernyi-106708277/?c=750000000#!/item",
    sortType: "phone",
    like:79
  },
  {
    id: 9,
    name: "Nokia 6300",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.2,
    images: 9,
    price: 29890,
    memory: 8,
    color: "white",
    kaspiLink: "https://kaspi.kz/shop/p/nokia-6300-ds-belyi-100875450/?c=750000000#!/item",
    sortType: "phone",
    like:578
  },
  {
    id: 11,
    name: "Electric kettle",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.4,
    images: 11,
    price: 6000,
    memory: 1.7,
    color: "white",
    kaspiLink: "https://kaspi.kz/shop/p/elektrochainik-monte-mt-1815g-belyi-108488533/?c=750000000#!/item",
    sortType: "household",
    like:5879
  },
  {
    id: 12,
    name: "Fridge KBC 390",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.8,
    images: 12,
    price: 224900,
    memory: 2.9,
    color: "green",
    kaspiLink: "https://kaspi.kz/shop/p/kleo-kbc-390-chb-belyi-104970651/?c=750000000#!/item",
    sortType: "household",
    like:798
  },
  {
    id: 13,
    name: "Microwave ARG MS-20",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.5,
    images: 13,
    price: 34425,
    memory: 4.7,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/arg-ms-2021m-chernyi-2900958/?c=750000000#!/item",
    sortType: "household",
    like:256
  },
  {
    id: 14,
    name: "Waffle iron DASH",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 2.5,
    images: 14,
    price: 34425,
    memory: 1.2,
    color: "red",
    kaspiLink: "https://kaspi.kz/shop/p/vafel-nitsa-dash-f-607-krasnyi-102531842/?c=750000000#!/item",
    sortType: "household",
    like:35
  },
  {
    id: 17,
    name: "Fridge HD 345RN",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.7,
    images: 17,
    price: 165990,
    memory: 3.2,
    color: "white",
    kaspiLink: "https://kaspi.kz/shop/p/artel-hd-345rn-steel-seryi-100531318/?c=750000000#!/item",
    sortType: "household",
    like:465
  }
  ,
  {
    id: 18,
    name: "Fridge Leadbros H",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.5,
    images: 18,
    price: 108400,
    memory: 4.2,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/leadbros-h-hd-122s-serebristyi-108343077/?c=750000000#!/item",
    sortType: "household",
    like:147
  },
  {
    id: 19,
    name: "Tire Tunga Zodiak",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3,
    images: 19,
    price: 10400,
    memory: 4.2,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/tunga-zodiak-2-185-65-r14-90t-bez-shipov-12701963/?c=750000000#!/item",
    sortType: "autoPr",
    like:222
  },
  {
    id: 20,
    name: "Tire Cordiant Sport",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.7,
    images: 20,
    price: 22900,
    memory: 4.2,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/cordiant-sport-3-195-65-r15-91v-bez-shipov-12701982/?c=750000000#!/item",
    sortType: "autoPr",
    like:456
  },
  {
    id: 21,
    name: "Свеча зажигания NGK",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 5,
    images: 21,
    price: 2490,
    memory: 1.2,
    color: "white",
    kaspiLink: "https://kaspi.kz/shop/p/svecha-zazhiganija-ngk-1578-lzkr6b10e-101064177/?c=750000000#!/item",
    sortType: "autoPr",
    like:357
  },
  {
    id: 22,
    name: "Свечные провода Tesla",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 3.9,
    images: 22,
    price: 15990,
    memory: 6,
    color: "red",
    kaspiLink: "https://kaspi.kz/shop/p/tesla-t927b-102878186/?c=750000000#!/item",
    sortType: "autoPr",
    like:951
  },
  {
    id: 23,
    name: "АвтоВАЗ универсальный",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.2,
    images: 23,
    price: 23200,
    memory: 3.7,
    color: "green",
    kaspiLink: "https://kaspi.kz/shop/p/avtovaz-universal-nyi-85320433-107536364/?c=750000000#!/item",
    sortType: "autoPr",
    like:654
  },
  {
    id: 24,
    name: "Универсальный 33156",
    description: "Fully unlocked and compatible with any carrier of choice (e.g. AT&T, T-Mobile, Sprint, Verizon, US-Cellular, Cricket, Metro, etc.). Tested for battery health and guaranteed to have a minimum battery capacity of 80%.",
    rating: 4.5,
    images: 24,
    price: 31400,
    memory: 4.7,
    color: "black",
    kaspiLink: "https://kaspi.kz/shop/p/avtovaz-model-nyi-210833402012-104009250/?c=750000000#!/item",
    sortType: "autoPr",
    like:628
  }
]
